### ISSUE TITLE
Übergreifend: Login

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#1]
**_Als Student möchte ich mich in die Anmeldung einloggen können damit ich meine Daten speichern und zu einem späteren Zeitpunkt erneut aufrufen kann._** 
_________________________________________
**Akzeptanzkriterien:** 

Wenn ich als Student die Anwendung aufrufe dann werde ich zu einer Login-Maske mit den folgenden Eingabefeldern / Buttons: 

- E-Mailadresse (Typ: E-Mailadresse) 
- Passwort (Typ: Passwort, nicht einsehbar)  
- Login (Typ: Button)  

Wenn der Loginversuch erfolgreich war werde ich zu der Startseite weitergeleitet  Wenn der Loginversuch fehlgeschlagen ist, verbleibe ich auf der Loginmaske und erhalte eine Fehlermeldung. 

_Hinweis: Die Benutzeranlage erfolgt durch einen eigenen Registrierungsprozess. Derzeit sind hierfür nur bestimmte Domains berechtigt. Zu einem späteren Zeitpunkt ist eine Anbindung an eine zentrale Benutzerverwaltung, z.B. LDAP, möglich._

**Comment by MartinaPauli** [comment]
Testfeedback: 
- Wenn ich  die Anwendung aufrufe, dann erreiche ich die Login-Maske nur über einen Extraklick auf Anmeldung. Besser wäre es, initial direkt zur Anmeldemaske zu gelangen. 
- Ansonsten alle Tests erfolgreich (siehe Testdokumentation). 
![2020-12-21 07_03_56-Window](https://user-images.githubusercontent.com/76420070/102744891-24000c80-435b-11eb-815a-10f487609541.png)
[SQM_Testdokumentation_Login.docx](https://github.com/bauersebastian/termplanner/files/5722565/SQM_Testdokumentation_Login.docx)
- Nach erfolgtem Login befindet sich der User auf der Seite "Mein Profil". Aus Gründen der Usability sollte er direkt aufs Dashboard geroutet werden (siehe auch User Story Dashboard).

**Comment by bauersebastian** [comment]
@MartinaPauli @Bjoern93 : Danke für die Anregungen! Beides habe ich umgesetzt.
Login jetzt direkt auf der Startseite verfügbar.
Nach dem Login landet man direkt auf dem Dashboard, anstatt im User Profil.

Bitte nochmals testen und ggf. abschließen.

Danke!
Sebastian

**Comment by MartinaPauli** [comment]
@bauersebastian @Bjoern93: 
Beide Anpassungen wurden erfolgreich getestet. Ich hab die Story auch gleich gelabelt.

Was mir unabhängig von der User Story noch aufgefallen ist: Wofür existiert überhaupt die Startseite? Brauchen wir die überhaupt?

**Comment by bauersebastian** [comment]
Ja, würde schon sagen ist üblich. Normalerweise würde man dort ein paar beschreibende Worte zur App finden. Also Funktionen kurz beschreiben, Marketingtexte etc...

**Comment by MartinaPauli** [comment]
Stimmt, macht schon Sinn.
@Bjoern93: Vielleicht sollten wir für die "Befüllung der Startseite mit Content" eine eigene UserStory erstellen. Mich hat das jedenfalls sehr irritiert, dass dort keine Inhalte zu finden waren.

**Comment by Bjoern93** [comment]
Regressionstests angelegt

**Comment by Bjoern93** [comment]
Story für den Startseitentext angelegt. @MartinaPauli erstellt den Text. Story wird geschlossen.

**Comment by Bjoern93** [comment]
/15

**Comment by Bjoern93** [comment]
https://github.com/bauersebastian/termplanner/issues/15
