### ISSUE TITLE
Studierender: PDF-Export der Terminplanung

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#10]
**_Als Studierender möchte ich die Termine meines Semesters ausdrucken können, damit ich eine Übersicht über die Machbarkeit meiner Module erhalte._** 
____________________
**Akzeptanzkriterien:** 
* Im Dashboard befindet sich ein Button für den PDF-Export 
* Nach einem Klick auf den Button wird ein PDF generiert mit den folgenden Inhalten 
    Überschrift: Meine Semesterplanung 
    - Tabellarische Darstellung der Termine des Studierenden mit den folgenden Spalten: 
    - Datum 
    - Modulbezeichnung 
    - Art der Abgabe (Skriptabarbeitung, Studienleistung, Klausur (Block A / Block B), Abstimmungstermine) 
    - Bezeichnung
    - Notiz 
- Die Sortierung erfolgt anhand des Datums

**Comment by bauersebastian** [comment]
Eine erste Version des PDF Exports ist fertig. Auf dem Dashboard kann ein DIN-A4 Blatt mit allen offenen Terminen ausgeben werden, gruppiert nach Modulen.

TODO: Anpassung Dateiname

**Comment by bauersebastian** [comment]
Dateiname wurde angepasst.
Known issue: Berücksichtigung der Zeitzone beim Export. Derzeit werden die Uhrzeiten in UTC ausgegeben.

**Comment by MartinaPauli** [comment]
@bauersebastian: PDF Export sieht sehr gut aus. Alle Akzeptanzkriterien sind aus meiner Sicht erfüllt.
[vawi_termine.pdf](https://github.com/bauersebastian/termplanner/files/5829285/vawi_termine.pdf)

**Comment by bauersebastian** [comment]
Die Korrektur bzgl. Zeitzone ist jetzt auch eingebaut. Es wird immer die Zeitzone des erfassten Termins ausgegeben. D.h. es wird die deutsche Zeit angegeben, auch wenn ich den Export in Australien starte.

**Comment by Bjoern93** [comment]
Auch von meiner Seite aus in Ordnung. Der Regressionstest testet nur das vorhanden sein des Buttons ab - eine Validierung des Inhalts erfolgt nicht.
