### ISSUE TITLE
Studierender: Mein Profil

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#13]
Als Studierender möchte ich meine E-Mailadresse und mein hinterlegtes Passwort bearbeiten können. 
___________________________________

- Wenn ich mich als Studierender auf der Startseite befinde dann kann ich über einen Klick auf ein Profil-Icon in der Navigationsleiste meine E-Mailadresse und mein Passwort bearbeiten. 
- Auf der Seite befinden sich die folgende Felder:    
    - Aktuelle E-Mailadresse (Typ: E-Mail) 
    - Neue E-Mailaldresse (Typ: E-Mail) 
    - Neues Passwort (Typ: Passwort) 
    - Neues Passwort (wiederholen) (Typ: Passwort) 
    - Speichern (Typ: Button) 
- Es ist möglich nur eine der beiden Angaben zu aktualisieren
    Nur E-Mail ausgefüllt: Nur die E-Mailadresse wird aktualisiert 
    Nur Passwort ausgefüllt: Nur das Passwort wird aktualisiert
    E-Mail & Passwort ausgefüllt: E-Mailadresse und Passwort werden aktualisiert 
- Das Feld "Neues Passwort (wiederholen)" wird nur validiert, wenn das Feld "Neues Passwort" ausgefüllt ist 
- Bei einer Aktualisierung der E-Mailadresse wird erneut der Bestätigungslink versendet

**Comment by Bjoern93** [comment]
Wireframe: https://marvelapp.com/prototype/bdida13/screen/74870335/handoff

**Comment by bauersebastian** [comment]
Funktionen stehen unter "Mein Profil" zur Verfügung. Möglichkeit zur Änderung des Passworts wurden mit dem letzten Commit hinzugefügt.

**Comment by MartinaPauli** [comment]
Bei einer Aktualisierung der E-Mailadresse wird kein erneuter Bestätigungslink versendet (siehe Doku).
[SQM_Testdoku_MeinProfil.docx](https://github.com/bauersebastian/termplanner/files/5722769/SQM_Testdoku_MeinProfil.docx)

**Comment by bauersebastian** [comment]
@MartinaPauli : Ein interessantes Problem, was ich auch bei manchen anderen E-Mail Providern gesehen habe.
Die Logs gaben folgenden Fehler aus:
Recipient address rejected: Mail appeared to be SPAM or forged. Ask your Mail/DNS-Administrator to correct HELO and DNS MX settings or to get removed from DNSBLs

Als Anbieter für den Mailversand wird mailgun.com verwendet. Damit alles reibungslos funktioniert, muss die DNS Konfiguration für die Domain vawi-planer.de aufgesetzt werden. 

In den Einträgen für die MX Records und CNAME Records waren die notwendigen Einträgen eigentlich vorhanden, aber leider fehlerhaft. Dadurch ging in im Aufruf der MX Records etwas schief (keine IP Adresse für die Mailserver wurde zurückgemeldet). 

Ist in den DNS Einstellungen zur Domain jetzt angepasst. Könnte allerdings 24 - 48 Stunden dauern, bis alle Anbieter die neuen Einstellungen ziehen.

Erneuter Test sollte spätestens ab Donnerstag möglich sein. Normalerweise funktioniert es innerhalb weniger Stunden.

**Comment by MartinaPauli** [comment]
@bauersebastian: 
Die Email wird nun umgehend versandt, allerdings in zweifacher Ausführung mit identischem Inhalt. Ziel ist, die Email nur einmal zu versenden (siehe ergänzte Doku mit Screenshots im Anhang). 
[SQM_Testdoku_MeinProfil.docx](https://github.com/bauersebastian/termplanner/files/5756546/SQM_Testdoku_MeinProfil.docx)

**Comment by bauersebastian** [comment]
@MartinaPauli : Das Verhalten ist in Ordnung so wie du das beschreibst. 
Wenn die E-Mail entfernt wird und dann eine neue E-Mail wieder hinzugefügt wird, wird immer eine E-Mail zur Bestätigung verschickt. D.h. es ist nicht notwendig nochmal manuell eine Bestätigung anzufordern. Wenn die E-Mail hinzugefügt wird, kommt auch die Meldung "Bestätigungs-E-Mail wurde an xyz@zzz.yy verschickt.". 

Man kann immer manuell eine neue Bestätigung anfordern, so oft man will. Denke daher kam die Doppelung der Mails.
Ich habe es selbst nochmal getestet. Nach dem Hinzufügen, ging direkt eine Mail raus. Eine zweite kommt nicht, insofern man nicht manuell eine weitere Bestätigung anfordert.

**Comment by MartinaPauli** [comment]
@bauersebastian: Danke für das Feedback. Deine Erklärung ist nachvollziehbar. Ich schließe die Story.

**Comment by Bjoern93** [comment]
@bauersebastian Die Änderung des Benutzernamens war ursprünglich nicht explizit angefordert. Finde ich aber in Ordnung. Kannst du bitte noch die folgende Anpassungen vornehmen? 

https://semesterplaner.herokuapp.com/users/XYZ/
- Ersetzen des Benutzernamens in "Mein Profil" durch "Profil bearbeiten" 
- Einfügen eines Textes "Nachfolgend hast du die Möglichkeit die Angaben in deinem Profil eigenständig zu aktualisieren." 
- Änderung des Buttons "Mein Profil" in "Mein Profil" in "Benutzername" ändern
- Änderung des Buttons "E-Mail" in "Mein Profil" in "E-Mail ändern" ändern

https://semesterplaner.herokuapp.com/users/~update/ 
- Ersetzen des Benutzernamens durch "Benutzername ändern" 
- Einfügen eines Textes: "Dein aktueller Benutzername lautet: XYZ" 
- Ändern des Labels "Name des Benutzers" in "Neuer Benutzername"
- Ändern des Buttons "Update" in "Benutzername ändern" 

https://semesterplaner.herokuapp.com/accounts/email/
- Ersetzen der Überschrift "E-Mailadressen" durch "E-Mailadresse ändern" 
- Bei den hinterlegten E-Mailadressen Slashes einfügen, also z.B. xyz.xyz@stud.uni-bamberg.de / Bestätigt / Primär
- Entfernen Button in einer eigenen Zeile

**Comment by bauersebastian** [comment]
Ist soweit erledigt.
Allerdings eine Sache muss ich aufklären: 
- man kann nicht den Benutzernamen ändern
- es ist einfach ein Name, den man dem Profil hinzufügen kann, völlig optional

Wenn der Name gepflegt ist, wird nun dieser im Profil angezeigt. Ansonsten der Benutzername.

**Comment by Bjoern93** [comment]
Passt aus meiner Sicht, danke. @MartinaPauli
