### ISSUE TITLE
Studierender: Modulpflege - Modul hinzufügen

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#14]
**_Als Studierender möchte ich neue Module hinzufügen und bearbeiten können, damit ich anschließend Termine erfassen kann._** 
_____________
**_Akzeptanzkriterien:_** 
* Unterhalb der Übersichtstabelle im Dashboard befindet sich ein Button "Modul hinzufügen" +
* Nach einem Klick auf den Button gelangt der Studierende auf eine Seite mit den folgenden Eingabefeldern:
   - Semester (Typ: List, Optionen: SoSe, WiSe) 
    - Modulbezeichnung (Typ: Liste, befüllt aus den hinterlegten Modulen) 
    - Punkte Studienleistung (Typ: Numerisch, max. 2 Stellen) 
    - Punkte Klausur (Typ: Numerisch, max. 2 Stellen) 
    - Note(Typ: Numerisch) 
* Abhängig von der Auswahl des Semesters werden dem Studierenden passende Modulbezeichnungen angezeigt (Module die nur im SoSe angeboten werden, werden nur angezeigt wenn SoSe ausgewählt ist) 
* Ist noch kein Semester ausgewählt ist keine Auswahl der Modulbezeichnung möglich 
* Nach einer Auswahl der Modulbezeichnung werden weitere Informationen eingeblendet: 
    - Anbieter 
    - Modulbeschreibung 
    - ECTS
    - Anteil WiWi
    - Anteil Informatik 
    - Anteil Wirtschaftsinformatik 
    - Anteil Schlüsselkompetenzen
* Unten rechts befindet sich ein Button "Speichern"

**Comment by Bjoern93** [comment]
Wireframe: https://marvelapp.com/prototype/bdida13/screen/74565625/handoff

**Comment by MartinaPauli** [comment]
Testfeedback:
- Das Feld "Term" bitte in "Semester" umbenennen und "Module" in "Modulbezeichnung"
- Abhängig von der Auswahl des Semesters werden dem Studierenden aktuell noch keine passende Modulbezeichnungen angezeigt (d.h. Module die nur im SoSe angeboten werden, werden aktuell auch angezeigt wenn WiSe ausgewählt ist)
[SQM_Testdoku_Modulpflege_Modul hinzufügen_0.1.docx](https://github.com/bauersebastian/termplanner/files/5723534/SQM_Testdoku_Modulpflege_Modul.hinzufugen_0.1.docx)

**Comment by bauersebastian** [comment]
Änderung der Bezeichnung ist umgesetzt. 
Abhängige Auswahl noch offen.

**Comment by bauersebastian** [comment]
Abhängige Auswahl ist nun auch umgesetzt.
Sobald ein Semester ausgewählt wurde, wird geprüft, welche Module im SS oder WS zur Verfügung stehen. Entsprechend wird die Dropdown Liste angepasst.

**Comment by bauersebastian** [comment]
@MartinaPauli bitte erneut testen. Insofern alles ok, bitte abschließen.

**Comment by MartinaPauli** [comment]
@bauersebastian @Bjoern93 Retest erfolgreich durchgeführt (siehe Doku).
[SQM_Testdoku_Modulpflege_Modul hinzufügen_01_Retest.docx](https://github.com/bauersebastian/termplanner/files/5753516/SQM_Testdoku_Modulpflege_Modul.hinzufugen_01_Retest.docx)

Eine Anregung noch zur Diskussion: Bei der Auswahl der Semester ggf. nur vergangene sowie das aktuelle und das nächste Semester zeigen. Aktuell ist die DropDown Liste sehr lange, weil die Auswahl weit in die Zukunft möglich ist.

**Comment by Bjoern93** [comment]
@bauersebastian Mir ist eben beim Erstellen der Regressionstests noch aufgefallen, dass im Frontend None ausgegeben wird, sofern keine Abschlussnote eingegeben wird und / oder die Felder Punkte Studienleistung / Punkte Abschlussnote leer gelassen werden. Kann man das noch anpassen und z.B. "-" einfügen?

![image](https://user-images.githubusercontent.com/12391701/103475466-a3ef9300-4dad-11eb-80c7-02d101ac9033.png)

**Comment by bauersebastian** [comment]
Wird bei der nächsten Version angepasst.

**Comment by bauersebastian** [comment]
Ist angepasst und auch live gesetzt.

**Comment by Bjoern93** [comment]
Regressionstestfälle erstellt. 

@bauersebastian Die Eingabefelder Punkte Studienleistung & Punkte Klausur sind noch vorbefüllt. Kannst du das noch anpassen? 
![image](https://user-images.githubusercontent.com/12391701/104132902-6d52e300-5380-11eb-98b0-e0cf29f81b18.png)

**Comment by MartinaPauli** [comment]
@bauersebastian/ @Bjoern93 
Was vereinbare wir bzgl. der DropDown-Liste zur Auswahl Semester? Aktuell ist die Auswahl bis weit in die Zukunft möglich. Ggf. macht es Sinn, nur das aktuelle und nächstfolgende Semester anzuzeigen? Mich irritiert diese ewiglange Liste total.

**Comment by bauersebastian** [comment]
@Bjoern93 Die Standardwerte, also die 0er Werte, sind entfernt. Dadurch sind die Felder jetzt leer bei der initialen Anlage.

**Comment by bauersebastian** [comment]
@MartinaPauli : ich habe die Drop Down Liste jetzt etwas reduziert. 
Das man etwas in die Vergangenheit gehen kann, hat den Sinn, dass man auch abgeschlossene Module noch erfassen kann. Somit sieht man wie viel man schon geschafft hat, kann Noten festhalten und man sieht im Dashboard die summierten ECTS Punkte. 

Das wäre dann auch die Basis für Berechnung von Notendurchschnitt oder die Berechnung der bisherigen Schwerpunkte (Informatik, Wirtschaftswissenschaften, etc.) - das ist dann recht leicht zu ergänzen.

**Comment by MartinaPauli** [comment]
@bauersebastian: Danke für die Reduzierung der DropDown-Liste. Jetzt sieht es sehr gut aus und ist übersichtlich. Von meiner Seite alles bestens.
@Bjoern: Bitte aus Sicht Regressionstest noch bewerten.

**Comment by Bjoern93** [comment]
Regressionstest erstellt.

**Comment by Bjoern** [comment]
Bitte nicht den falschen Björn taggen, Danke :-)
