### ISSUE TITLE
Übergreifend: Einführungstext

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#15]
Text als Teaser worum es geht

**Comment by MartinaPauli** [comment]
Textvorschlag für Startseite 
[VAWIPlaner_Marketingtext.docx](https://github.com/bauersebastian/termplanner/files/5860483/VAWIPlaner_Marketingtext.docx)

**Comment by Bjoern93** [comment]
@bauersebastian Danke für das Einfügen. Kann man das Anmeldeformular auf der Startseite noch entweder rechts in einer zweiten Column einfügen oder komplett entfernen?

**Comment by Bjoern93** [comment]
Anmerkung: Im explorativen Test kam noch die Anmerkung hinzu, dass ein Bild eingefügt werden soll. Vorschlag: Wir verwenden dieses Bild - am besten direkt unter der Überschrift einfügen. 

https://pixabay.com/de/photos/sch%C3%BCler-eingabe-tastatur-text-849825/

**Comment by bauersebastian** [comment]
@Bjoern93 : Bild ist eingefügt. Anmeldemaske auf Startseite war im Verlauf des Projektes ein expliziter Wunsch. Ich habe es jetzt kleiner gestaltet, aber linksbündig gelassen.
Entfernen ginge natürlich jederzeit.

**Comment by Bjoern93** [comment]
@bauersebastian  Danke dir - bitte den Login auf der Startseite dann ausblenden.

**Comment by MartinaPauli** [comment]
Ich finde es (analog zu Björn) auch stimmiger, die Loginmaske auf der Startseite auszublenden. 
Der User wird intuitiv auf den "Anmelden"-Button drücken und nicht nach unten scrollen.

@bauersebastian: Kannst du die Anmeldemaske noch ausblenden, damit wir dann das Ticket auch schließen können?

**Comment by bauersebastian** [comment]
@Bjoern93 @MartinaPauli 
Ist erledigt mit dem Ausblenden!

**Comment by MartinaPauli** [comment]
Sieht jetzt super aus, danke @bauersebastian!
