### ISSUE TITLE
Anpassung der Navigation

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#17]
**_Als Endbenutzer möchte ich, dass der Navigationspunkt "Anmeldung" in "Anmelden" umbenannt wird. Außerdem soll der Punkt "Startseite" ausgeblendet werden, sobald ich eingeloggt bin, damit ich mich leichter zurechtfinde. Der Button "Abmelden" soll sich ganz rechts befinden._** 
___________________
**Akzeptanzkriterien:** 
- Aus den exlorativen Tests heraus kam das Feedback, dass die Navigation nicht intuitiv ist, daher sollen die folgenden Anpassungen vorgenommen werden: 
    - Umbenennung des Navigationspunkts "Anmeldung" in "Anmelden" 
    - Ausblenden des Navigationspunkts "Startseite" nach dem Login
    - Der Navigationspunkt "Abmelden" soll sich ganz rechts befinden.

**Comment by bauersebastian** [comment]
Ist umgesetzt.

**Comment by Bjoern93** [comment]
Umsetzung passt aus meiner Sicht - FYI @MartinaPauli

**Comment by MartinaPauli** [comment]
Test erfolgreich.
