### ISSUE TITLE
Layoutoptimierung: Modul

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#18]
**_Als Endbenutzer möchte ich, dass der Modulname kleiner geschrieben wird und die Buttons rechtsbündig angezeigt werden, damit die Seite benutzerfreundlicher wird._** 
___________________
**Akzeptanzkriterien:** 

- Aus den exlorativen Tests heraus kam das Feedback, dass es noch Optimierungspotenzial auf der Modulübersicht:
    - Der Modulname soll anstatt in H1 in H2 angezeigt werden
    - Die Buttons "Modul ändern" und "Modul löschen" sollen rechtsbündig abschließen und somit identisch zum Button "Termin hinzufügen" positioniert werden

![image](https://user-images.githubusercontent.com/12391701/105636948-0991e500-5e6b-11eb-9dd9-1c988a683209.png)

**Comment by bauersebastian** [comment]
Ist umgesetzt und damit korrigiert.

**Comment by Bjoern93** [comment]
Danke für die Anpassung, danke dir. @MartinaPauli Auch hier gerne noch einmal drauf schauen und das Ticket danach  schließen.

**Comment by MartinaPauli** [comment]
Test erfolgreich.
