### ISSUE TITLE
Layoutoptimierung: Dashboard

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#19]
**_Als Endbenutzer möchte ich, dass in der Modulübersicht zusätzlich das Semester angezeigt wird, damit ich auch kommende Semester planen kann und leicht die Übersicht behalte._** 
___________________
Akzeptanzkriterien: 
- Aus den explorativen Tests heraus kam das Feedback, dass das Semester in der Modulübersicht (Dashboard) eingeblendet werden soll:
    - Einfügen einer Spalte "Semester" am Anfang der Tabelle 
    - Die Sortierung erfolgt nach Semester, Modulbezeichnung

**Comment by bauersebastian** [comment]
Ich habe das Semester aufgenommen.
Dafür habe ich in der Ansicht der nicht abgeschlossenen Module die Note und die ECTS entfernt. Diese Info bringt ja keinen wirklichen Mehrwert dort.
Die Sortierung ist auch angepasst.
Erst nach Semester, dann aber nach Anzahl der offenen Termine (das war ja mal eine Anforderung aus den anderen Stories).

**Comment by Bjoern93** [comment]
Umsetzung passt, danke dir! @MartinaPauli  Bitte auch noch einmal drauf schauen und das Ticket dann gerne schließen.

**Comment by MartinaPauli** [comment]
Test erfolgreich.
