### ISSUE TITLE
Übergreifend: Footer

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#2]
**_Als Otto-Friedrich-Universität Bamberg möchte ich im Footer die rechtlich notwendigen Angaben einbinden, damit ich rechtsicher unterwegs bin und keine Sorge vor Abmahnungen haben muss._**
______________________
**Akzeptanzkriterien:**

Auf allen Seiten der Webseite ist ein Footer eingebunden, welcher die folgenden Informationen enthält: 

- Impressum
- Datenschutzhinweise

**Comment by bauersebastian** [comment]
Die Seiten wurden hinzugefügt. Text müsste noch eingefügt werden.

**Comment by MartinaPauli** [comment]
Test erfolgreich.

Impressum und Datenschutzhinweise sind von allen Unterseiten aus erreichbar.

**Comment by Bjoern93** [comment]
Regressionstest angelegt.
