### ISSUE TITLE
Studierender: Benutzerregistrierung

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#3]
**_Als Student möchte ich mich für die Anmeldung registrieren können, damit ich auf die Anwendung zugreifen kann._**
__________________________
**Akzeptanzkriterien:**

- Wenn ich als Student die Anwendung aufrufe habe ich die Möglichkeit mich durch einen Klick auf den Navigationspunkt "Registrieren" für die Anwendung registrieren zu können.
- Die Registrierungsseite beinhaltet die folgenden Inhalte: 
    Überschrift: Registrierung 
    E-Mailadresse (Typ: E-Mail, Pflichtfeld)
    Anmeldename (Typ: Text, Pflichtfeld)
    Passwort (Typ: Passwort, Pflichtfeld) 
    Passwort (wiederholen) (Typ: Passwort, Pflichtfeld) 
    Registrieren (Typ: Button) 
- Nach dem Klick auf "Registrieren" wird eine Erfolgsmeldung angezeigt
- Nach dem Klick auf "Registrieren" wird eine E-Mail zur Bestätigung der E-Mailadresse versendet

**Comment by bauersebastian** [comment]
Diese Funktion ist implementiert:
Test unter - https://www.vawi-planer.de/accounts/signup/
E-Mail wird nach Registrierung verschickt.

**Comment by MartinaPauli** [comment]
Test erfolgreich (siehe Doku).
[SQM_Testdoku_Benutzerregistrierung_0.3.docx](https://github.com/bauersebastian/termplanner/files/5722646/SQM_Testdoku_Benutzerregistrierung_0.3.docx)
