### ISSUE TITLE
Administration: Modulstammdaten verwalten

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#4]
**_Als VaWi-Sekretariat möchte ich Module in dem Semesterplaner pflegen können, damit die Studierenden die Module entsprechend  auswählen können._**
_____________________________
**Akzeptanzkriterien:** 
* Als VaWi-Sekretariat möchte ich ein Frontend zur Verfügung haben, über das ich neue Module erstellen / bearbeiten kann: 
    - Modulname  
    - Anbieter  
    - Beschreibung 
    - Angebotszeitraum (Eingabe: SoSe, WiSe, Jederzeit)    
    - ECTS 
    - Anteil WiWi (in %)  
    - Anteil Informatik (in %)  
    - Anteil WI (in %)  
    - Anteil Schlüsselkompetenzen (in %)  
* Löschen ist auch möglich

**Comment by Bjoern93** [comment]
Zu prüfen: Alternative Umsetzung über FE

**Comment by bauersebastian** [comment]
Alle o.g. Felder wurden eingebaut und können im Admin Backend verwaltet werden. 
Löschen ist auch möglich.

**Comment by MartinaPauli** [comment]
@bauersebastian: Hast aktuell nur du Zugriff auf das Admin Backend?

**Comment by bauersebastian** [comment]
@MartinaPauli : Ich habe dich freigeschalten und eine Rolle "Stammdatenverwaltung" erstellt. Damit kann man die Moduldaten pflegen.
Adresse: https://www.vawi-planer.de/uniadmin/ 

Bitte mit deinem Benutzer der Uni Mail Adresse anmelden. Wenn ein anderer Benutzer berechtigt werden soll, bitte Bescheid geben.

Teste bitte mal, ob es wie gewünscht funktioniert.

Danke!
Sebastian

**Comment by Bjoern93** [comment]
![Module -- Gespeicherte Werte sollen korrekt übernommen werden](https://user-images.githubusercontent.com/12391701/104132761-b191b380-537f-11eb-94f1-27ff79cc5c83.png)

@bauersebastian Mir ist beim Erstellen der Regressionstestfälle noch folgendes aufgefallen: 

1. Nach der Anlage eines neuen Moduls ist die Tabelle leer, das sieht etwas unschön aus. Können wir die Tabelle ausblenden, wenn noch kein Termin hinterlegt ist und einen Text anzeigen "Es wurden noch keine Termine hinterlegt."?
2. Bei den Punkten machen die Kommazahlen keinen Sinn - kann das noch angepasst werden? 
3. Die Einrückung bei "Belegt im ..." ist noch ein Darstellungsfehler. Kann man das eventuell aus der Tabelle herausnehmen und als Überschrift verwenden?

**Comment by Bjoern93** [comment]
Intialen Regressionstestfälle erstellt.

**Comment by MartinaPauli** [comment]
@bauersebastian: Ich habe die Modulstammdaten mit dem Adminstratorenuser getestet. Folgendes Feedback.
- Hinzufügen und Löschen von Modulen funktioniert grds. Lediglich kleinere Schönheitskorrekturen (Großschreibung/andere Formulierung der Buttons) erforderlich.
- Änderung von Modulen nicht möglich. 
Details findest du in der Testdoku.
Hinweis: Ich habe das Modul "Projektmanagement" zuerst gelöscht und dann mit anderen Inhalten hinzugefügt. Die beiden Module "Plattformökonomie" und "Wissensmanagement" wurden gelöscht.
[SQM_Testdokumentation_Administration_Modulstammdaten verwalten_4.docx](https://github.com/bauersebastian/termplanner/files/5796044/SQM_Testdokumentation_Administration_Modulstammdaten.verwalten_4.docx)

**Comment by bauersebastian** [comment]
@Bjoern93 
Wenn keine Termine vorhanden wird nun ein Satz eingeblendet, statt der leeren Tabelle.
"Belegt im..." ist nun eine H5 Überschrift. Dieser Absatz ist gleich eingerückt wie "Termine", die "Modulüberschrift" oder "Angaben zum Modul" - 15 px Padding. War bisher auch nicht in der Tabelle inkludiert.

Die Punkte als Float statt Integer eingeben zu können, macht meines Erachtens Sinn, da ich selbst schon Ergebnisse mit Kommawerten bekommen habe. Dozenten bewerten gerade Studienleistungen manchmal nach striktem Schema und dabei entstehen teilweise Ergebnisse mit zwei Nachkommastellen. Von daher würde ich das so belassen.

**Comment by bauersebastian** [comment]
@MartinaPauli : Danke für den Test!
Ich habe die Bezeichnung angepasst. Das Admin Backend generiert sich automatisch aus dem Code. Deswegen können nicht alle Anpassungen so ganz genau vorgenommen werden. Aber es ist jetzt fast durchgängig alles korrekt bezeichnet bei den Modulen (außer wenn man nur ein Modul löscht, ist das nicht ganz perfekt im Deutschen).

Die Anpassung für die Semester nehme ich nicht mehr vor. Ich hoffe du kannst mit SS/WS leben statt SoSe/WS. Bei einer Anpassung daran, müsste man die Datenbank migrieren. Das steht nicht im Verhältnis zum Nutzen, da diese Auswahl nur die Key-User sehen.

Beim Bearbeiten:
Hier ist es einfach notwendig, auf das Modul, also den Titel zu klicken. Dann kommst du in die Bearbeitung rein. Die Auswahl oben ist nur optional, falls man etwas löschen möchte. Die Bearbeitung ist immer eine Einzelauswahl (nicht mehrere). 

Ich hoffe ich habe somit alle offenen Punkte bearbeitet. Falls nicht, bitte melden.

**Comment by MartinaPauli** [comment]
@bauersebastian: Danke für das Feedback und die Anpassungen. Ich habe mir alles nochmal angeschaut, sieht für mich sehr gut aus. 
@Bjoern93: Falls Regressionstest auch erfolgreich, bitte Ticket schließen.
