### ISSUE TITLE
Studierender: Modulpflege - Notenverwaltung

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#5]
**_Als Studierender möchte ich meine Noten in der Semesterplanung hinterlegen können, damit ich in einem späteren Entwicklungszyklus auf weitere Funktionen, wie zum Beispiel die Studienplanung mit der Berechnung der Durchschnittsnote, zugreifen kann._** 
____________________
**Akzeptanzkriterien:** 
- Nach einem Klick auf den Modulnamen im Dashboard kann ich als Studierender in folgenden Feldern Eingaben tätigen:
-- Modul-Note (Typ: Text, dreistellig) 
-- Klausur-Punkte (Typ: Nummerisch, zweistellig) 
-- SL-Punkte (Typ: Nummerisch, zweistellig) 
-- Speichern (Typ: Button) 
-- Alle Felder können leer bleiben

**Comment by Bjoern93** [comment]
Umsetzung in https://github.com/bauersebastian/termplanner/issues/14

**Comment by MartinaPauli** [comment]
Test erfolgreich.
![Studierender_Modulpflege_Notenverwaltung](https://user-images.githubusercontent.com/76420070/102767873-861f3880-4380-11eb-9e61-343a2e79e038.png)
![Studierender_Modulpflege_Notenverwaltung_Felder sind keine Pflichtfelder](https://user-images.githubusercontent.com/76420070/102767986-b666d700-4380-11eb-8c1b-ed8faefe165f.png)
