### ISSUE TITLE
Studierender: Dashboard

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#6]
Als Studierender möchte ich nach dem Login ein Dashboard vorfinden auf dem die relevanten Informationen zusammengefasst sind, damit ich mein Semester erfolgreich abschließen kann. 
___________________________________________________-
**Akzeptanzkriterien:** 

- Überschrift: "Mein Semester"
- Darunter befindet sich eine tabellarische Übersicht der eingepflegten Module, mit den folgenden Angaben: 
    - Modulbezeichnung 
    - ECTS 
    - Note 
    - Nächste Termine 
    - Zur Planung
- Unter "Nächste Termine" werden die nächsten drei Termine eines Moduls als Liste angezeigt
- Unter "Zur Planung" befindet sich ein Button
- Die Sortierung n der Modultabelle erfolgt nach folgenden Kriterien: 
    - Ganz oben werden noch nicht abgeschlossene Module angezeigt 
    - Die Sortierung erfolgt ansonsten alphabetisch 
- Ein Klick auf den Modulnamen oder den Button "Zur Planung" führt zu der Terminplanung für das Modul (https://github.com/bauersebastian/termplanner/issues/7) 
- Unterhalb der Tabelle befindet sich die Überschrift "Terminübersicht" 
- Hierunter befindet sich ein Kalenderwidget, in welchem die Termine gesammelt angezeigt werden: 
    - Links: Kalenderübersicht 
    - Rechts: Tabellarischer Überblick mit den folgenden Spalten: 
        - Datum
        - Modulbezeichnung 
        - Art
        - Bezeichnung
        - Notiz  
    - Die Sortierung der Tabelle erfolgt nach dem Datum

**Comment by Bjoern93** [comment]
Wireframe: https://marvelapp.com/prototype/bdida13/screen/74870085/handoff

**Comment by MartinaPauli** [comment]
Testfeedback:
- Aktuell gelangt man nach erfolgreichem Login auf die Seite „Mein Profil“ und ruft das Dashboard über einen Extraklick auf den Button „Dashboard“ auf. Aus Gründen der Usability wäre es besser, nach dem Login direkt ins Dashboard zu gelangen.
- Überschrift: "Mein Semester" (aktuell: Meine Semester)
- Tabellarische Übersicht: 
   o	Nächste Termine (Überschrift wird nicht komplett angezeigt)
   o	Zur Planung (der Button ist nicht verfügbar)
- Unter "nächste Termine" werden aktuell alle in einem Modul eingepflegten Termine in der Liste angezeigt, es ist keine Beschränkung auf die nächsten drei hinterlegt.
- Aktuell führt nur der Klick auf den Modulnamen zur Terminplanung des Moduls. Da der Button "Zur Planung" noch nicht existiert, funktioniert diese Alternative nicht.
- Unterhalb der Tabelle befindet sich die Überschrift "Terminübersicht" (aktuelle Bezeichnung: Termine)
- Im Kalenderwidget sind die Spalten "Modulbezeichnung" und "Art" vertauscht.
- In der Kalenderübersicht wird aktuell nur die Terminbezeichnung übernommen (z.B. Klausur Block A), so dass man in der Kalenderübersicht, wo sich die Termine aller eingepflegten Module vermischen, keine Eindeutigkeit mehr hat. Ggf. Schulungshinweis, dass die Terminbezeichnungen immer mit dem Kürzel des Moduls beginnen sollten (z.B. SQM, DCM etc.). @Sebastian: Oder gibt es eine bessere, systemseitige Lösung?
- Aktuell werden auch noch bereits abgelaufene Termine in der tabellarischen Kalenderübersicht angezeigt. Verschwinden diese Termine erst, wenn man sie auf erledigt gesetzt hat? Aktuell ist ein Setzen auf erledigt nicht möglich.

**Comment by bauersebastian** [comment]
@MartinaPauli @Bjoern93 
Das Dashboard habe ich nun überarbeitet - bitte schaut es euch nochmal an und gebt gerne Feedback, was besser gemacht werden kann. 

In der Liste der aktuellen Module, werden nun nur noch die nächsten 3 offenen Termine angezeigt.

Im Kalender wird der heutige Tag jetzt markiert, das Modulkürzel (aus den Stammdaten) + Terminbezeichnung angezeigt.
Im Kalender tauchen nur offene Termine auf.

Frage: Sollen auch abgeschlossene Termine auftauchen? Ggf. durchgestrichen oder ausgebaut zu Informationszwecken?

In der tabellarischen Übersicht aller Termine, tauchen auch nur unerledigte Termine auf. Ein Termin muss auf erledigt gesetzt werden, damit er in der Liste verschwindet.
Wie im Kalenderwidget auch, ist hier die Frage, wie ihr es haben wollt. 

Durch einen Klick in der Tabelle kommt man direkt zum Termin, um ihn zu bearbeiten. Das gleiche im Widget.

**Comment by bauersebastian** [comment]
Eine weitere Frage wäre noch: 
Soll im Widget ggf. auch der Endtermin dargestellt werden? Also wenn ein Endtermin an einem anderen Tag liegt als der Starttag z.B. Rot darstellen oder irgendwie anders?

**Comment by MartinaPauli** [comment]
@bauersebastian: Bzgl. der Akzeptanzkriterien hab ich nur kleinere Anmerkungen/Schönheitskorrekturen (siehe Testdoku ganz unten). Ansonsten konnte ich die Sortierung im Dashboard in meinem Beispiel nicht nachvollziehen. Obwohl in einem Modul alle Termine erledigt waren, wurde das Modul ganz oben einsortiert. Bitte nochmal prüfen.

Zu deinen Fragen: 
- Abgeschlossene Termine würde ich nicht mehr anzeigen. Das Dashboard soll dem User ja visualisieren, was noch offen ist. Insofern finde ich es aktuell sinnvoll umgesetzt.
- Bzgl der Darstellung der Endtermine: Ja hier sollten wir uns noch etwas überlegen. Mich irritiert es aktuell total, dass ich bei dem im Widget angezeigten Terminen nicht weiß, ob das ein Start- oder Endtermin ist. Es wird ja aktuell nur der Starttermin angezeigt, aber das ist dem User denke ich beim Betrachten des Widgets nicht sofort klar. Von daher würde ich im Falle einer Zeitspanne sowohl Start- als auch Endtermin anzeigen und entsprechend visualisieren (Starttermin grün/Endtermin rot).
@Bjoern93: Bitte auch nochmal prüfen, ob du das auch so sinnvoll hälst.
[SQM_Testdoku_Dashboard.docx](https://github.com/bauersebastian/termplanner/files/5797324/SQM_Testdoku_Dashboard.docx)

**Comment by bauersebastian** [comment]
@MartinaPauli @Bjoern93 
Das Dashboard habe ich jetzt nach euren Vorschlägen umgebaut.
Zudem habe ich den Kalender nochmal anders implementiert. Ich denke das löst die genannten Probleme recht gut. Schaut es einfach mal an.

**Comment by MartinaPauli** [comment]
@bauersebastian: Das Dashboard und v.a. das Kalenderwidget finde ich insgesamt sehr schön umgesetzt (v.a. dass der aktuelle Tag gelb markiert ist und die Zeitspannen im Widget visualisiert werden ist klasse). 

Was mich allerdings noch irritiert ist die Übersicht unter dem Widget. Da hier nur die Starttermine angezeigt werden, frage ich mich grad, welchen Mehrwert die Übersicht im Vergleich zum Dashboard bietet. 
@Bjoern93: Kannst du dir das bitte nochmal anschauen. Ich tendiere dazu, entweder dort auch den Endtermin anzuzeigen oder die Übersicht ggf. komplett wegzulassen.

**Comment by Bjoern93** [comment]
@bauersebastian Bitte auch das Enddatum anzeigen. Ansonsten passt die Seite aus meiner Sicht. Die Sortierung sollte nach dem Enddatum erfolgen.

**Comment by bauersebastian** [comment]
Endedatum ist nun eingebaut.
Sortierung nach Endedatum ist schwierig, da diese Information optional ist.
Was passiert, wenn kein Endedatum vorhanden?
Sortierung aktuell nach Startdatum.

**Comment by Bjoern93** [comment]
Daran hatte ich nicht gedacht. Passt aus meiner Sicht

**Comment by MartinaPauli** [comment]
Passt auch aus meiner Sicht.
