### ISSUE TITLE
Studierender: Modulpflege - Terminverwaltung

### ISSUE THREAD

**Issue by Bjoern93** [bauersebastian/termplanner#7]
**_Als Studierender möchte ich die Möglichkeit haben die Termine für ein Modul planen zu können, damit ich eine Übersicht über die Machbarkeit meiner gewünschten Module erhalten._**
_____________
**Akzeptanzkriterien:** 

* Nach einem Klick auf den Modulnamen im Dashboard gelange ich auf eine Seite zur Bearbeitung eines Moduls
* Der Abschnitt befindet sich unterhalb des Abschnitts "Meine Modulverwaltung" und oberhalb des Abschnitts "Allgemeine Modulangaben"
* Überschrift des Abschnitts: Semester planen
* Tabellarische Übersicht zu den bisher geplanten Terminen des Moduls:
    - Datum
    - Art (Skriptabarbeitung, Studienleistung, Klausur (Block A / Block B), Abstimmungstermine)
    - Bezeichnung
    - Notiz
    - Erledigt am
    - Aktion (Typ: Liste, Optionen: Bearbeiten, Löschen) 
* Unterhalb der Tabelle befinden sich die folgenden Felder: 
    -  Datum (Typ: Datumsauswahl)
    - Art (Typ: Liste, Optionen: Skriptabarbeitung, Studienleistung, Klausur (Block A / Block B), Abstimmungstermine)
    - Bezeichnung (Typ: Text) 
    - Notiz (Typ: Textfeld) 
    - Erledigt am (Typ: Checkbox) 
* Wird die Aktion "Bearbeiten" ausgewählt, werden die unten stehenden Felder ausgefüllt 
* Wird die Aktion "Löschen" ausgewählt wird der Eintrag gelöscht

**Comment by Bjoern93** [comment]
Wireframe: https://marvelapp.com/prototype/bdida13/screen/74565892/handoff

**Comment by Bjoern93** [comment]
Als neue Seite umsetzen

**Comment by bauersebastian** [comment]
Die Übersicht zum Modul ist nun aufgeräumt. Sie entspricht weitestgehend den Vorgaben (Bearbeitung der Termine auf separater Seite) + den Sachen, die schon realisiert waren.

Ihr könnt nun testen.

**Comment by MartinaPauli** [comment]
@Bjoern93: Bitte auch nochmal drüberschauen. Es wurde nicht alles so umgesetzt, wie es in der Anforderung beschrieben ist. Trotzdem finde ich es sehr sinnvoll realisiert.
@bauersebastian: Eine Unklarheit aus meiner Sicht. Ich kann keinen Termin löschen (für den Fall, dass ich einen Termin hinzugefügt habe, den ich dann für irrelevant halte). Testdoku anbei.
[SQM_Testdoku_Modulpflege_Terminverwaltung_#7.docx](https://github.com/bauersebastian/termplanner/files/5797109/SQM_Testdoku_Modulpflege_Terminverwaltung_.7.docx)

**Comment by bauersebastian** [comment]
@MartinaPauli Die Möglichkeit einen Termin zu löschen, gab es schon. Allerdings nur unter den Termin Details, wenn man in der Übersicht auf den Namen des Termins geklickt hat.

Ich habe es jetzt so erweitert, dass man in der Terminbearbeitung auch zum Löschen abspringen kann. Somit ist die Möglichkeit jetzt auch dort gegeben.
Zudem noch etwas Kosmetik: Bei einer Terminänderung ist die Überschrift jetzt eine andere, als bei der Terminerfassung.

**Comment by MartinaPauli** [comment]
@bauersebastian: Danke für die Anpassungen. Keine weitere Beanstandung von meiner Seite, finde das Termin löschen nun sehr schön und userfreundlich umgesetzt.
![Termin löschen_180121](https://user-images.githubusercontent.com/76420070/104882476-6ff69f00-5963-11eb-95cb-5c793ecc3003.png)

**Comment by Bjoern93** [comment]
Umsetzung passt aus meiner Sicht. Regressionstests wurden erstellt.
